<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
        content="{{ isset($metas) && $metas->meta_description ? $metas->meta_description : setting('meta_description') }}">
    <meta name="keywords"
        content="{{ isset($metas) && $metas->meta_keywords ? $metas->meta_keywords : setting('meta_keywords') }}">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{{ isset($metas) && $metas->meta_title ? $metas->meta_title : setting('meta_title') }}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta property="og:url" content="{{ url()->current() }}" />
    <meta property="og:type" content="article" />
    <meta property="og:image"
        content="{{ isset($metas) && $metas->image ? asset('ruploads/' . $metas->image) : public_asset('website/img/default-share.jpg') }}" />
    <meta property="og:title"
        content="{{ isset($metas) && $metas->page_title ? $metas->page_title : setting('meta_title') }}" />
    <meta property="og:description"
        content="{{ isset($metas) && $metas->meta_description ? $metas->meta_description : setting('meta_description') }}" />
    @yield('header')

    <link rel="shortcut icon" href="{{ public_asset('website/img/logo.png') }}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
        integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="{{ public_asset('website/landing/css/style.css') . '?' . now() }}">
    <style>
        .red-border {
            border: 1px solid red !important;
        }

        select.red-border,
        .g-recaptcha.red-border {
            border: 0 !important;
        }

        .g-recaptcha.red-border>div {
            border: 1px solid red !important;
        }

        select.red-border+span {
            border: 1px solid red !important;
        }
    </style>
    @yield('css')
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @if (setting('extras.google_site_tag'))
        @php
            $site_tag = setting('extras.google_site_tag');
        @endphp
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ $site_tag }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];

            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());

            gtag('config', '{{ $site_tag }}');
        </script>
    @endif
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json"> { "@context" : "http://schema.org", "@type" : "LocalBusiness", "name" : "Traveladventurenepal.pty.ltd.", "image" : "https://www.traveladventurenepal.com.au/ruploads/1538474951.everest.jpg", "telephone" : "+61449669224", "email" : "enquiries@traveladventurenepal.com.au", "address" : { "@type" : "PostalAddress", "streetAddress" : "Suite 502/155 Castlereagh Street", "addressLocality" : "Sydney", "addressRegion" : "New South Wales", "addressCountry" : "Australia", "postalCode" : "2000" }, "url" : "https://www.traveladventurenepal.com.au/" } </script>
    <script>
        (function(h, e, a, t, m, p) {
            m = e.createElement(a);
            m.async = !0;
            m.src = t;
            p = e.getElementsByTagName(a)[0];
            p.parentNode.insertBefore(m, p);
        })(window, document, 'script', 'https://u.heatmap.it/log.js');
    </script>
    @if (setting('extras.google_tag_manager_code'))
        @php
            $tag_manager_code = setting('extras.google_tag_manager_code');
        @endphp
        <!-- Google Tag Manager -->
        <script>
            (function(w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({
                    'gtm.start': new Date().getTime(),
                    event: 'gtm.js'
                });
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s),
                    dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', {{ $tag_manager_code }})
        </script>
        <!-- End Google Tag Manager -->
    @endif
</head>

<body>
    @if (setting('extras.google_tag_manager_code'))
        <!-- Google Tag Manager (noscript) -->
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id="{{ $tag_manager_code }} height="0"
                width="0" style="display:none;visibility:hidden"></iframe></noscript>
        <!-- End Google Tag Manager (noscript) -->
    @endif
    <div class="loader">
        <div class="insideloader">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    {{ menu('landing-top', 'website::menu.landing-top') }}

    @yield('content')

    @yield('otherContent')
    <footer>
        <div class="topfooter">
            <div class="container-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 subscribewrap">
                            <div class="col-md-7 col-sm-12 col-lg-7 col-xl-7 col7 leftcontent">
                                <img data-src="{{ public_asset('website/landing/img/shape.png') }}"
                                    class="img-fluid lazy">
                                <p>Subscribe to get more deals like this!</p>
                                <p>Enter your email address and get all the deals & updates in your inbox.</p>
                            </div>
                            <div class="col-md-5 col-sm-12 col-lg-5 col-xl-5 col5 rightcontent">
                                <form method="post" id="subscribe-form"
                                    action="{{ route('website.subscribe.post') }}">
                                    @csrf
                                    <div class="input-group">
                                        <input type="email" name="email" class="form-control"
                                            placeholder="Enter email address" required>
                                        <div class="input-group-append">
                                            <span class="input-group-text">
                                                <button type="submit" class="btn btn-primary">SUBSCRIBE
                                                    <img data-src="{{ public_asset('website/landing/img/subimg.png') }}"
                                                        class="img-fluid lazy">
                                                </button>
                                            </span>

                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="bottomfooter">
            <div class="container-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 content">
                            <p>&copy; Copyright. All Rights Reserved. Travel Adventure PTY.LTD &nbsp; ABN no:
                                57623409674 &nbsp;&nbsp; <a data-toggle="modal" data-target="#termsModal">Terms and
                                    Conditions</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- Modal -->
    <div class="modal fade termsModal" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="termsModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <img data-src="{{ public_asset('website/landing/img/logo.png') }}" class="lazy">
                    <h3 class="modal-title" id="termsModalLabel">Bookings Term and Conditions</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Please Take Time to Read and Understand the Conditions of Booking set Out below prior making a
                        commitment to Book a Trip with Us. We Strongly Recommend that you Also read The Essential Trip
                        Information Relating to Your Trip Prior your Bookings to Ensure that you Understand the
                        Itinerary, Style and Physical Demand your Trip requires that you will Undertaking.</p>
                    <ol>
                        <li><b>Our Contract:</b>&nbsp;Doko Tours Pty Ltd is a Licensed Travel Agent in Australia. These
                            Terms and Conditions (The Agreement) Describe What You are Legally Entitled to Expect from
                            Us When You Purchase Travel Related Services through us, in Addition to Your Obligations as
                            A Customer. The Terms “We”, “Us” and “Our” Refer to Doko Tours Pty Ltd. The Term “You”
                            Refers to the Customer Visiting Our Website, booking a Reservation Through us or Otherwise
                            Using Our Services.</li>
                        <li><b>Insurance:</b>&nbsp;Adequate and Valid Travel Insurance is Compulsory for All travellers
                            and it is the Condition of an Accepting your Booking that You agree You Will Have Obtain
                            Adequate and Valid Travel Insurance for Your Booking by the Date of Departure. Your Travel
                            Insurance Must Cover Accidents, Injury, illness and Death Medical Expenses, including any
                            Related to Pre-Existing Medical Conditions, Emergency Repatriation (Including Helicopter
                            Rescue and Air Ambulance Where Applicable). We also Recommends that your Insurance Also
                            Covers Trip Cancellation, Curtailment and Loss of Luggage and Personal Effects. We Holds
                            Every Reserves to Cancel or suspend your Participation or Commencement of your Trip with No
                            Right of Refund If you are Unable to Provide Proof of Insurance When Requested.</li>
                        <li><b>Deposit Requirement:</b>&nbsp;100% Deposit for the trip is required which includes
                            International Flight tickets.</li>
                        <li><b>Acceptance of Bookings and Final Payments:</b>&nbsp;Accepting the bookings, the
                            confirmation invoice will be issued. A contract will exists between you and us from the date
                            the confirmation invoice is issued.</li>
                        <li><b>Price and Surcharge:</b>&nbsp;As a standard practise in Travel industry, the price may
                            varies in any of our Packages. “Everest Base Camp in May” is a promotional event so support
                            the Visit Nepal 2020 campaign. There might be chances of creating more deals to attract the
                            travellers for certain time. Any Reduced pricing or discounts that may available after you
                            booking will not be applied in your bookings. If you wish to cancel the bookings to take
                            advantage of deal, your bookings will cancel under full cancellation policy. Please be
                            advised, Surcharge might be applied to all purchases made by credit cards.</li>
                        <li><b>Cancellation by the Traveller:</b>&nbsp;Cancelling some part or all portions of bookings,
                            cancellation charge applies on the date request. A cancellation policy will only be
                            effective when we receive the written confirmation of the cancellation.<br>
                            If You Cancel the Trip:
                            <ul>
                                <li><b>Between 56-30 Days Prior to Departure:</b>&nbsp;50% of Total Booking Cost Plus
                                    any Air Ticket Cancellation Charge</li>
                                <li><b>Between 30-18 Days Prior to Departure:</b>&nbsp;80% of Total Booking Cost Plus
                                    any Air Ticket Cancellation Charge</li>
                                <li><b>18 Days Prior to Departure:</b>&nbsp;100% of Total Booking Cost Plus any Air
                                    Ticket Cancellation Charge</li>
                            </ul>
                            We Strongly Advised to Take Out the Cancellation Insurance at the Time of Booking Which Will
                            Cover Cancellation Fees. If you leave a Trip for any Reason after it has commenced, we are
                            not obligated to make any Refunds of Unused Services. If you fail to Join a Tour, join it
                            After Departure or Leave It Prior to its Completion, no refund will be made.
                        </li>
                        <li><b>Cancellation by Us:</b>&nbsp;Doko Tours Pty Ltd Reserves the Right to Cancel any Trip You
                            Booked, Including a Guaranteed Trip Prior to Departure Due to Reasons Beyond its Control
                            I.e. Natural Disasters, Flight Cancellation, Consequences of Strikes, Industrial Action,
                            Wars, Riots. Government Intervention or Any External events which Viable for Us is not to
                            operate the Planned Trips. If we cancel Your Trip, you can transfer amounts paid to an
                            Alternate Departure date or receive a Full Refund. Airlines Fare organised by us for the
                            Trip will be refunded or can be changed to Other Date of You Transfer to an Alternate
                            Departure Date free of Cost. We are not responsible for any Incidental Expenses or
                            Consequential Losses that you may have incurred because of the Booking Such as Visas,
                            Vaccinations, Travel Insurance or Non-Refundable Flights (Not Booked through Us).</li>
                        <li><b>Booking Amendment:</b>&nbsp;If We Received the Booking Amendment Request at Least 56 Days
                            Prior of Departure Which Included Transfer One trip to Another or Transfer your Booking to
                            Third Party, A standard Fee will be Apply (in Addition to any Charges levied by Hotels,
                            Ground Handlers or Airlines). If Booking Amendment is Request Less than 56 Days Prior of
                            Departure the Change Fee May Be Higher Depending Upon Company’s Arrangement with Hotels,
                            Airlines and Ground Operator. No Amendment is authorized to your Booking within 15 Days of
                            Departure. Flight Amendment is Subject to Rules of Airlines and May Charge Accordingly.
                            Changes to Name Details are not allowed by Many Airlines. While we will Endeavour Make Such
                            a Change if Necessary, please bear in Mind that Most of Airlines treat a Name Change as a
                            Cancellation, to Which Standard Conditions and Charges Would Apply.</li>
                        <li><b>Tour Leader Authority:</b>&nbsp;Booking With us and Accepting our Terms Indicate your
                            Agreement to Stand by the Authority of the Leader, who Represents Doko Tours Pty Ltd. The
                            Decision of the Leader as to the Conduct Itinerary and Objectives of the Tour is Final. If,
                            in the Opinion if the Leader, your Behaviour or Physical Condition is Unfavourable to the
                            Safety, Welfare and Well-Being of the Group as a Whole (Which are the Paramount
                            Considerations), or if the leader Considers your General Well Being will be put at Risk by
                            Continuing with the Holiday, you may Be asked to leave the Tour without the Right to any
                            Refund or Unused Services.</li>
                        <li><b>Inclusions and Exclusions:</b>&nbsp;All Inclusions and Exclusions are listed in Each
                            Programs on Our Websites. Services requested to be added from Exclusions to Programs are
                            subject to be charged accordingly.</li>
                        <li><b>Accommodation:</b>&nbsp;Any Accommodation We Arrange for you must only be used by those
                            People named Under the Confirmation Invoice (or on Latest Amendment invoice Issued). You are
                            not allowed to Share the accommodation or let anyone Else Stay with you. You are Responsible
                            for the Cost of any Damage Caused to your Accommodation or its Contents during your Stay.
                            These Charges must be Met by you and May have to be Paid Locally.</li>
                        <li><b>Optional Activities:</b>&nbsp;Optional Activities Not Included in Trip Price does not
                            form of the Trip or Contract. Any Additional Activities arranged by you with Local
                            Representatives are Liable within you and Organizer.</li>
                        <li><b>Age and Health Requirement:</b>&nbsp;All our Trips Minimum Age Requirement is 15 at the
                            time of Travel. All Travellers under the Age of 18 Years old should be escort by the
                            Travellers over the Age of 18 that can be Legal Guardians or designee Appointed by Legal
                            Guardians. If legal Guardians elect to designate an escort, they will be required to
                            complete and Sign a Relevant Document, to delegate their Authority. We do not have any Upper
                            Age Limits for most of Our Trips though we remind you that Our Trips are physically
                            demanding and Travellers Must Ensure that you are suitably fit to Allow Full Participation.
                            It is your Responsibility to ensure that you obtain Proper and Detailed Medical Advice at
                            Least 2 months prior to Travel for the latest Health Requirements and Recommendation for
                            Your Destination.</li>
                        <li><b>Medical and Special Requirement:</b>&nbsp;The Company Must be Notified at the Time of
                            Booking of any Medical Conditions, Physically Challenged Conditions or Any Other Mental and
                            Or Physical Condition which may Affect Fitness to Travel and any Medical Conditions. Failure
                            to Notify the Company May Result in the Client being Refused Travel or Cancellation which
                            may Result in 100% Cancellation fees to the Client. Some Trips may be unsuitable for Clients
                            due to Age, Mobility, Pregnancy or Physical or Mental Conditions. It is the Client’s
                            Responsibility to Check Prior to Booking. The Company is not required to provide any Special
                            Facilities Unless it has agreed to do so in Writing. The Company will do its best to meet
                            Clients Special Requests Include Dietary, but Such Requests do not form Part of the Contract
                            and therefore the Company is not Liable for not providing these Requests.</li>
                        <li><b>Passport, Visa and Immigration Document:</b>&nbsp;You Must have a Valid Passport and Have
                            Obtained the Appropriate Visa When Travelling with Doko Tours. Please Ensure your Passport
                            is Valid for 6 Months beyond the Duration of Trip. Nepal Visa is Available on Arrival in
                            Nepal. It is your Responsibility to ensure that you are in Possession of the Correct Visa
                            for the Countries you are Travelling to. We are not responsible if you are Refused entry to
                            a Country or Places because you Lack Correct Visa, Passport or Travel Document. Please Carry
                            4-5 Passport Size Photo with you during the Trip Required for Trekking passes and National
                            Park Permit.</li>
                        <li><b>Local Laws, Custom and Travel Aware:</b>&nbsp;Laws and Customs of Nepal can be Different
                            to those in Australia. Be aware of your Actions to ensure that they do not offend,
                            especially if you intend to Visit Religious Area. There may be Serious Penalties for doing
                            something that might not be Illegal in Australia. National Park and Protected Area of Nepal
                            have Very Strictly Laws. All above these things, Our Tour Leader will explain the Rules and
                            Regulations Prior to Trip. You are also Recommended to Read the <a
                                href="http://smartraveller.gov.au/Countries/asia/south/Pages/nepal.aspx">http://smartraveller.gov.au/Countries/asia/south/Pages/nepal.aspx</a>
                            for further Information.</li>
                        <li><b>Change of Itinerary:</b>&nbsp;While We Endeavour to operate all Trips as Described We
                            Reserve the Right to Change the Trip Itinerary. Please Refer to Our Website before Departure
                            for the Most Recent Updates to your Itinerary. Before Departure if we make a Major Change,
                            we will inform you. While a major Change is made you, may choose between accepting the
                            Change, obtaining a Refund of money or accepting an Alternative Tour Offered. After
                            Departure if any Emergency Circumstances Takes Place we will be providing the Alternative
                            Itinerary minimizing the Additional Cost as Possible. Please note we are not responsible for
                            any Incidental Expenses that may be incurred because of the Change of Itinerary Such as
                            Visas, Vaccinations or Non-Refundable Flights.</li>
                        <li><b>Injury and Evacuation:</b>&nbsp;Doko Tours’s Trekking guide is well trained in first Aid.
                            But none of the trekking guides or team members are allowed to give the medication to
                            victims. However, there is always a stand by evacuation service in worst case Scenario. Doko
                            Tours would not be liable to any cost expenses during the injury or health conditions.<br>
                            Hence, Travellers are advised to take Adequate Insurance Packages, including Medical
                            Emergencies and Evacuation by Helicopter.
                        </li>
                        <li><b>Claims and Complains:</b>&nbsp;If you have a problem during your Trip, you must inform
                            your Tour Leader who will endeavour to put things first. If your Complaint is not Solved
                            Locally, please follow this up within 28 Days of your Return Home, giving your Booking
                            reference and Relevant Information. It is Strongly Suggested that you communicate any
                            Complaint to your Tour Leader without Delay and Complete a Report Form Whilst on the Tour.
                            If you fail to follow this Simple Procedure we will have been deprived of the opportunity to
                            Investigate and Rectify your Complain during your Trip and this may affect your Rights under
                            the Contract.</li>
                        <li><b>Photos and Marketing:</b>&nbsp;You consent to us using images of you Taken during the
                            Trip for Advertising and Promotional Purposes in any Medium We Choose. You Grant us a
                            Perpetual, Royalty-Free, Worldwide License to use Such Images for Publicity and Promotional
                            Purposes.</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- modal -->
    <!-- bookingform -->
    <div class="booking-form" id="booking-form">
        <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 top position-relative">
            <div>
                <h3>Everest Base Camp In May</h3>
                <span>Travel Deal-May 2019</span>
            </div>
            <span aria-hidden="true" class="closebtn">&times;</span>
        </div>
        <!--top-->
        <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 form">
            <form action="{{ route('website.landing.post') }}" method="post" class="w-100" id="book-Form">
                @csrf
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <select id="title" class="js-example-basic-single form-control" name="title">
                        <option value="" disabled selected>Title </option>
                        <option value="Mr" {{ old('title') == 'Mr' ? 'selected' : '' }}>Mr</option>
                        <option value="Mrs" {{ old('title') == 'Mrs' ? 'selected' : '' }}>Mrs</option>
                        <option value="Miss" {{ old('title') == 'Miss' ? 'selected' : '' }}>Miss</option>
                        <option value="Ms" {{ old('title') == 'Ms' ? 'selected' : '' }}>Ms</option>
                    </select>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" id="first_name" name="first_name" placeholder="First Name"
                        value="{{ old('first_name') }}" required>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" id="middle_name" name="middle_name" placeholder="Middle Name"
                        value="{{ old('middle_name') }}">
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" id="last_name" name="last_name" placeholder="Last Name"
                        value="{{ old('last_name') }}" required>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="email" name="email" id="email" placeholder="Email Address"
                        value="{{ old('email') }}" required>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    @include('website::partials.country-list', [
                        'class' => 'js-example-basic-single form-control',
                        'noneText' => 'Nationality',
                        'required' => 'required',
                        'name' => 'nationality',
                        'selectId' => 'nationality',
                        'value' => old('nationality'),
                    ])
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <select id="gender" class="js-example-basic-single form-control" name="gender">
                        <option value="" disabled selected>Gender</option>
                        <option value="male" {{ old('title') == 'male' ? 'selected' : '' }}>Male</option>
                        <option value="female" {{ old('title') == 'female' ? 'selected' : '' }}>Female</option>
                        <option value="other" {{ old('title') == 'other' ? 'selected' : '' }}>Other</option>
                    </select>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" name="address" id="address" placeholder="Address Line"
                        value="{{ old('address') }}" required>
                </div>
                <div class="clearfix"></div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" name="second_address" id="second_address" placeholder="Address Line 2"
                        value="{{ old('address') }}">
                </div>

                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" id="phone_number" name="phone_number"
                        placeholder="Contact number (mobile)" value="{{ old('phone_number') }}">
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="number" id="number_of_person" name="number_of_person"
                        placeholder="Number Of Person" value="{{ old('number_of_person') }}" required>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" name="state" placeholder="State/province" id="state"
                        value="{{ old('state') }}" required>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="number" name="postal_code" placeholder="Postal Code" id="postal_code"
                        value="{{ old('postal_code') }}" required>
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    @include('website::partials.country-list', [
                        'class' => 'js-example-basic-single form-control',
                        'noneText' => 'Country',
                        'required' => 'required',
                        'name' => 'country',
                        'selectId' => 'country',
                        'value' => old('country'),
                    ])
                </div>
                <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                    <input type="text" name="coupon_code" placeholder="Coupon Code (If applicable)"
                        id="coupon_code" value="{{ old('coupon_code') }}">
                </div>
                <div class="clearfix"></div>
                <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 col12">
                    <textarea name="message" id="message" rows="4" placeholder="Anything else you would like to specify..">{{ old('message') }}</textarea>
                </div>
                <div class="col-md-12 col-sm-12 col-lg-12 col-xl-12 bottom nopadding">
                    <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6">
                        <div class="g-recaptcha" data-theme="light"
                            data-sitekey="6LcQtmYUAAAAAF3Nv9kthnzCJok1nVg5uMaFgo8O"></div>
                    </div>
                    <div class="col-md-6 col-sm-12 col-lg-6 col-xl-6 col6 butn book_btn">
                        <button type="submit" class="btn btn-primary submitbtn">Submit</button>
                    </div>
                </div>
            </form>
        </div>
        <!--form-->
    </div>
    <!-- bookingform -->
    <a href="javascript:" id="return-to-top"><i class="fas fa-arrow-up"></i></a>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-beta.2/lazyload.js"></script>
    <script  src="{{ public_asset('website/landing/js/style.js').'?'.now()}}"></script>
    <script  src="{{ public_asset('website/landing/js/timer.js')}}?"></script>
    {{-- <script src="{{ public_asset('website/js/style.js').'?'.now()}}"></script> --}}
    <script >
    $(document).ready(function() {
        $('.js-example-basic-single').select2();
        $('.dates').datepicker({
            format:'yyyy-mm-dd',
            startDate: new Date()
        });
        // $('#subscribe-form').submit(function (e) {
        //     e.preventDefault();
        //     $.post($(this).attr('action'),$(this).serialize(),function (data) {
        //         if(data.alert_type=='error'){
        //             toastr.error(data.message);
        //         }else{
        //             toastr.success(data.message)
        //         }
        //     }).fail(function (err) {
        //         toastr.error(err.responseJSON.errors.email[0]);
        //     })
        // });
    });
    $("img.lazy").lazyload({
        threshold : 200
    });
</script>

    @if (Session::has('message'))
        <script>
            console.log('me');
            toastr.{{ Session::get('alert-type') }}("{{ Session::get('message') }}");
        </script>
    @endif
    @if ($errors->any())
        <script>
            var errors = {!! json_encode($errors->getMessages()) !!};
            $.each(errors, function(k, v) {
                var attrId = k.replace(/\./g, "_");
                console.log(attrId);
                if (attrId == 'g-recaptcha-response') {
                    $(".g-recaptcha").addClass('red-border');
                } else {
                    $("#" + attrId).addClass('red-border');
                }

            });
            $(".book").trigger('click');
            toastr.error("You Have Error In you Input");
        </script>
    @endif

    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    </script>
    @yield('js')
</body>

</html>
