<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Doko Tours | Book detail 1</title>
    <link rel="shortcut icon" href="{{ public_asset('website/img/logo.png') }}">

    <!-- Bootstrap -->
    <link href="{{ public_asset('website/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ public_asset('website/css/animate.css') }}">
    <link href="{{ public_asset('website/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">
    <link href="{{ public_asset('website/css/hover.css') }}" rel="stylesheet" media="all">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ public_asset('website/css/owl.carousel.min.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.min.css" />
    <link rel="stylesheet" href="{{ public_asset('admin/bower_components/select2/css/select2.min.css') }}" />
    <link rel="stylesheet" href="{{ public_asset('website/css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" type="text/css" href="{{ public_asset('website/css/spritestyle.css').'?'.now()}}">
    <link rel="stylesheet" type="text/css" href="{{ public_asset('website/css/style.css') }}?">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <style>
        .form-error{
            color: #fc3657;
            font-family: 'Poppins', sans-serif;
            font-weight: 400;
            margin-top: 5px;
        }
         .red-border{
             border:1px solid red !important;
         }

    </style>
    @yield('css')
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    @if(setting('extras.google_site_tag'))
        @php
            $site_tag = setting('extras.google_site_tag');
        @endphp
        <script async src="https://www.googletagmanager.com/gtag/js?id={{ $site_tag }}"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', '{{ $site_tag }}');
        </script>
@endif
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. --> <script type="application/ld+json"> { "@context" : "http://schema.org", "@type" : "LocalBusiness", "name" : "Traveladventurenepal.pty.ltd.", "image" : "https://www.traveladventurenepal.com.au/ruploads/1538474951.everest.jpg", "telephone" : "+61449669224", "email" : "enquiries@traveladventurenepal.com.au", "address" : { "@type" : "PostalAddress", "streetAddress" : "Suite 502/155 Castlereagh Street", "addressLocality" : "Sydney", "addressRegion" : "New South Wales", "addressCountry" : "Australia", "postalCode" : "2000" }, "url" : "https://www.traveladventurenepal.com.au/" } </script>
    <script>
        (function(h,e,a,t,m,p) {
            m=e.createElement(a);m.async=!0;m.src=t;
            p=e.getElementsByTagName(a)[0];p.parentNode.insertBefore(m,p);
        })(window,document,'script','https://u.heatmap.it/log.js');
    </script>
    @if(setting('extras.google_tag_manager_code'))
        @php
            $tag_manager_code = setting('extras.google_tag_manager_code');
        @endphp
    <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer',{{ $tag_manager_code }});</script>
        <!-- End Google Tag Manager -->
    @endif
</head>
<body>
@if(setting('extras.google_tag_manager_code'))
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id="{{ $tag_manager_code }}
        height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
@endif
<div class="loader">
    <div class="insideloader">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<div class="container-fluid book-nav">
    <div class="container">
        <div class="row">
            <div class="site-logo">
                <a href="{{ route('website.home') }}">
                <img src="{{ public_asset('website/img/logo.png') }}" class="img-responsive" alt="">
                </a>
            </div>
            <div class="book-steps">
                <ul>
                    <li><a href="{{ route('website.book.init',['trip'=>$trip->slug,'departure'=>isset($departure->id)?$departure->id:'new','start_date'=>isset($booking)?$booking->start_date->format('Y-m-d'):request()->get('start_date')]) }}" class="{{ $step=='first'?'active':'' }}">1. Traveller Information ............</a></li>
                    <li><a href="{{ ($step=='first')?'#':route('website.booking.features',['booking'=>Crypt::encrypt($booking->id)]) }}" class="{{ $step=='second'?'active':'' }}">2. Options/Arrangements ............</a></li>
                    <li><a href="{{ ($step=='first')?'#':route('website.booking.review',['booking'=>Crypt::encrypt($booking->id)]) }}" class="{{ $step=='third'?'active':'' }}">{{ isset($departure->id)?'3.':'2.' }} Payment </a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<main id="main">
    <div class="container-fluid paddingtb book-body">
        <div class="container">
            @yield('content')
        </div>
    </div>
    @include('website::layouts.footer')
</main>

@include('website::partials.auth-modal');
<script>function addLoadEvent(o){var n=window.onload;"function"!=typeof window.onload?window.onload=o:window.onload=function(){n&&n(),o()}}</script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{ public_asset('website/js/bootstrap.min.js') }}"></script>
{{--<script >--}}
    {{--$(function () {--}}
        {{--$('.dates').datepicker({--}}
            {{--format: 'YYYY/MM/DD',--}}
        {{--});--}}
    {{--});--}}
{{--</script>--}}
<script >
    $(document).ready(function() {
        $('.loader').delay(1500).hide(0);
    });
</script>
<script src="{{ public_asset('website/js/bootstrap-slider.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
 <script src="{{ public_asset('website/js/classie.js') }}"></script>
 <script src="{{ public_asset('website/js/owl.carousel.min.js') }}"></script>
 <script src="{{ public_asset('website/js/parallax.min.js') }}"></script>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script  src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<!-- Select 2 js -->
<script src="{{ public_asset('admin/bower_components/select2/js/select2.full.min.js') }}"></script>
<script src="{{ public_asset('admin/bower_components/bootstrap-multiselect/js/bootstrap-multiselect.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
@if(!Auth::check())
    @if($errors->register->any())
        <script>
            $(document).ready(function () {
                $("#loginModal").modal('show');
                $("#create-account").trigger('click');
            });

        </script>
    @endif

    @if($errors->reset->any())
        <script>
            $(document).ready(function () {
                $("#loginModal").modal('show');
                $("#reset-password").trigger('click');
            });

        </script>
    @endif
    @if($errors->login->any())
        <script>
            $(document).ready(function () {
                $("#loginModal").modal('show');

            });

        </script>
    @endif
@endif
@yield('js')
<script src="{{ public_asset('website/js/style.js') }}"></script>
</body>
</html>