<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 10/8/18
 * Time: 10:05 PM
 */

namespace App\Data\Models;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Request;

class CustomRequest extends Model
{

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'passenger_count',
        'group_type',
        'children_present',
        'start_date',
        'days_count',
        'activities',
        'description',
        'request_type',
        'destination',
        'desired_cost_per_person',
        'flight_country_from',
        'accommodation_styles',
        'accommodation_standards',
        'meal_preference',
        'referral_source',
        'contact_options',
        'ip',
        'travelling',
        'adult_present',
        'infant_present',
        'interested',
        'budget_optimization',
        'budget_range',
        'full_name',
        'nationality',
        'state',
        'about_us',
        'guide',
        'end_date'
    ];

    public static function boot()
    {
        static::saving(function ($model){
            $model->ip = Request::ip();
            $model->activities = is_array($model->activities)?implode(',',$model->activities):'';
            $model->accommodation_styles = is_array($model->accommodation_styles)?implode(',',$model->accommodation_styles):'';
            $model->contact_options = is_array($model->contact_options)?implode(', ',$model->contact_options):'';
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function getNameAttribute($value)
    {
        return $this->first_name.' '.$this->last_name;
    }

}