<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 8/27/18
 * Time: 1:06 PM
 */

namespace App\Data\Models;


use Illuminate\Database\Eloquent\Model;

class CustomField extends Model
{

    protected $fillable = [
        'key',
        'title',
        'value',
        'icon',
        'type',
        'extras'
    ];

//    protected $casts = [
//        'extras'=>'array'
//    ];
    public static function boot()
    {
        static::saving(function($model){
            $model->key = str_slug($model->title);

        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function faqs()
    {
        return $this->hasMany(Faq::class,'category_id','id');
    }

}