<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 7/27/18
 * Time: 1:47 PM
 */

namespace App\Data\Models;


use App\Data\Traits\ListableRepoTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Request;

class Enquiry extends Model
{

    use ListableRepoTrait;
    protected $fillable = [
        'name',
        'email',
        'subject',
        'message',
        'ip',
        'issue'
    ];

    public $indexColumns = [
        'name',
        'email',
        'subject',
    ];

    public static function boot()
    {
        static::saving(function ($model){
            $model->ip = Request::ip();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }
}