<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 7/19/18
 * Time: 12:18 PM
 */

namespace App\Data\Models;


use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ExtraValue extends Model
{

    use SoftDeletes;
    
    protected $fillable = [
        'addable_id',
        'addable_type',
        'key',
        'value',
        'extras',
        'slug',
        'type'
    ];

    public static function boot()
    {

        static::saving(function($model){
            $model->slug = str_replace(' ','-',rtrim(strtolower($model->key)));
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function setSlugAttribute()
    {
        $this->attributes['slug'] = str_replace(' ','-',rtrim(strtolower($this->key)));
    }

    public function addable()
    {
        return $this->morphTo();
    }



}