<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 8/21/18
 * Time: 1:41 PM
 */

namespace App\Data\Models;


use App\Data\Traits\ListableRepoTrait;
use Illuminate\Database\Eloquent\Model;

class FlightBooking extends Model
{

    use ListableRepoTrait;

    protected $fillable = [
        'departure',
        'arrival',
        'flight_type',
        'departure_date',
        'return_date',
        'adults',
        'number_of_pax',
        'passengers',
        'flexible_date',
        'first_name',
        'last_name',
        'email',
        'nationality',
        'message'
    ];

    public $indexColumns = [
        'first_name',
        'departure',
        'arrival',
        'flight_type',
        'departure_date',
        'return_date',
        'email',
        'nationality'

    ];

    public static function boot()
    {
        static::saving(function ($model){
            $model->number_of_pax = array_sum(array_values($model->passengers));
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    protected $casts = [
        'passengers'=>'array'
    ];
}