<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 2/28/19
 * Time: 12:08 PM
 */

namespace App\Data\Models;


use App\Data\Traits\ListableRepoTrait;
use Illuminate\Support\Facades\Request;
use Illuminate\Database\Eloquent\Model;

class LandingInquiry extends Model
{
    use ListableRepoTrait;
    protected $fillable = [
        'title',
        'first_name',
        'middle_name',
        'last_name',
        'email',
        'phone_number',
        'gender',
        'address',
        'second_address',
        'nationality',
        'message',
        'country',
        'state',
        'postal_code',
        'number_of_person',
        'coupon_code',
        'ip'
    ];

    public $indexColumns = [
        'name',
        'email',
        'address',
        'nationality',
        'phone_number',
        'coupon_code',
    ];


    public static function boot()
    {
        static::saving(function ($model){
            $model->ip = Request::ip();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function getNameAttribute($value)
    {
        return $this->title.' '.$this->first_name.' '.($this->middle_name)?$this->middle_name.' ':''.$this->last_name;
    }
}