<?php
/**
 * Created by PhpStorm.
 * User: nbin
 * Date: 7/26/18
 * Time: 12:13 PM
 */

namespace App\Data\Models;


use App\Data\Traits\AttachableTrait;
use App\Data\Traits\OfferableTrait;
use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{

    use OfferableTrait,AttachableTrait;
    protected $fillable = [
        'offerable_id',
        'offerable_type',
        'offerable_title',
        'start_date',
        'finish_date',
        'title',
        'link',
        'remaining',
        'discount',
        'publish',
    ];

    public static function boot()
    {
        static::saving(function($model){
            $model->offerable_title = $model->offerable->title;
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function offerable()
    {
        return $this->morphTo();
    }

    /**
     * @param $query
     * @return mixed
     */
    public function scopeActive($query)
    {
        return $query->where('start_date','<=',now())->where('finish_date','>=',now())->where('publish',1)->orderBy('start_date','asc');
    }

}